/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#7bd0ff",
        "error-dim": "#bb5551",
        "secondary-dim": "#8f9fb7",
        "surface-container-low": "#06122d",
        "on-secondary": "#102134",
        "primary-fixed-dim": "#a2dcff",
        "error": "#ee7d77",
        "inverse-primary": "#00668b",
        "surface-container": "#05183c",
        "secondary-fixed-dim": "#c5d6f0",
        "on-primary-container": "#97d8ff",
        "primary-fixed": "#c4e7ff",
        "primary-container": "#004c69",
        "on-primary": "#004560",
        "secondary-fixed": "#d3e4fe",
        "tertiary-fixed": "#f8a010",
        "surface-container-highest": "#00225a",
        "on-primary-fixed": "#00445e",
        "on-tertiary-fixed": "#2a1700",
        "on-error-container": "#ff9993",
        "on-tertiary-fixed-variant": "#563400",
        "on-background": "#dee5ff",
        "background": "#060e20",
        "on-surface-variant": "#91aaeb",
        "surface-tint": "#7bd0ff",
        "surface-container-lowest": "#000000",
        "surface-container-high": "#031d4b",
        "on-secondary-container": "#b0c0da",
        "on-tertiary": "#573500",
        "on-tertiary-container": "#4a2c00",
        "on-error": "#490106",
        "outline": "#5b74b1",
        "on-surface": "#dee5ff",
        "on-primary-fixed-variant": "#006286",
        "outline-variant": "#2b4680",
        "tertiary-fixed-dim": "#e79400",
        "primary-dim": "#47c4ff",
        "inverse-surface": "#faf8ff",
        "secondary-container": "#2d3c51",
        "tertiary-dim": "#e79400",
        "surface-dim": "#060e20",
        "surface": "#060e20",
        "on-secondary-fixed": "#314055",
        "tertiary-container": "#f8a010",
        "secondary": "#8f9fb7",
        "error-container": "#7f2927",
        "inverse-on-surface": "#4d556b",
        "tertiary": "#ffb148",
        "on-secondary-fixed-variant": "#4d5d73",
        "surface-variant": "#00225a",
        "surface-bright": "#002867"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
